name: Line Count on Master Push (with cloc)

on:
  push:
    branches:
      - master

jobs:
  count-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install cloc
        run: sudo apt-get install -y cloc

      - name: Count Lines with cloc
        run: cloc .