name: PHP_CodeSniffer

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --no-scripts --prefer-dist

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=Squiz --sniffs=Squiz.Commenting.FunctionComment src/
